### Site info:
title: 清热解读
tagline: Hello and Welcome to Qingre.com
author: Kirk Young
email: afanty@gmail.com
description: "Qingre.com is a Jekyll blog." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "qingre, 清热, 清热解读"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://qingre.com/blog" # the base hostname & protocol for your site
locale: zh_CN

### Personal info and site tools info:
twitter_username: foous
github_username:  foous
disqus_shortname: foous
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Kirk Young. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/dpSKQ92.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: ""
      Archives: "存档"
      Blogroll: "链接"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Sukui's Domain
      href: http://sukui.com/
      title: Sukui's Domain name


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
permalink: /:year/:month/:title.html